// Code generated by protoc-gen-joymicro. DO NOT EDIT.
// source: gmtool.proto

package api_gmtool

import (
	"context"
	"fmt"
	"github.com/golang/protobuf/proto"
	"math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// GmToolServiceInterface 服务调用接口
type GmToolServiceInterface interface {
	Placehold(context.Context, *PlaceholdReq) (*PlaceholdRes, error)
}

// NewGmToolService 创建服务调用
func NewGmToolServiceInstance() GmToolServiceInterface {
	// 本地函数调用模式，用于调试
	return &gmToolServiceLocal{}
}

// GmToolHandlerInterface 服务节点handler接口定义
type GmToolHandlerInterface interface {
	Placehold(context.Context, *PlaceholdReq, *PlaceholdRes) error
}

// NewGmToolHandler 创建并注册、运行一个服务
func NewGmToolHandler(handler GmToolHandlerInterface) error {
	gmToolHandlerLocal = handler
	return nil
}

// ============================================调试模式变量============================================

var gmToolHandlerLocal GmToolHandlerInterface

// gmToolServiceLocal 本地函数调用，用于调试
type gmToolServiceLocal struct{}

func (c *gmToolServiceLocal) Placehold(ctx context.Context, in *PlaceholdReq) (*PlaceholdRes, error) {
	var out *PlaceholdRes = new(PlaceholdRes)
	var err error
	err = gmToolHandlerLocal.Placehold(ctx, in, out)
	return out, err
}
