// Code generated by protoc-gen-joymicro. DO NOT EDIT.
// source: user.proto

package api_user

import (
	"context"
	"fmt"
	"github.com/golang/protobuf/proto"
	"math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// UserServiceInterface 服务调用接口
type UserServiceInterface interface {
	Placehold(context.Context, *PlaceholdReq) (*PlaceholdRes, error)
}

// NewUserService 创建服务调用
func NewUserServiceInstance() UserServiceInterface {
	// 本地函数调用模式，用于调试
	return &userServiceLocal{}
}

// UserHandlerInterface 服务节点handler接口定义
type UserHandlerInterface interface {
	Placehold(context.Context, *PlaceholdReq, *PlaceholdRes) error
}

// NewUserHandler 创建并注册、运行一个服务
func NewUserHandler(handler UserHandlerInterface) error {
	userHandlerLocal = handler
	return nil
}

// ============================================调试模式变量============================================

var userHandlerLocal UserHandlerInterface

// userServiceLocal 本地函数调用，用于调试
type userServiceLocal struct{}

func (c *userServiceLocal) Placehold(ctx context.Context, in *PlaceholdReq) (*PlaceholdRes, error) {
	var out *PlaceholdRes = new(PlaceholdRes)
	var err error
	err = userHandlerLocal.Placehold(ctx, in, out)
	return out, err
}
